// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package datastore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	Key    string      `json:"key"`
	Data   []byte      `json:"data"`
	Expiry pgtype.Int4 `json:"expiry"`
}

type Url struct {
	ID        int32            `json:"id"`
	ShortUrl  string           `json:"short_url"`
	LongUrl   string           `json:"long_url"`
	AuthorID  pgtype.Int4      `json:"author_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID           int32            `json:"id"`
	Username     string           `json:"username"`
	Email        string           `json:"email"`
	Password     []byte           `json:"password"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	PasswordSalt []byte           `json:"password_salt"`
}

type Visit struct {
	ID        int32            `json:"id"`
	UrlID     pgtype.Int4      `json:"url_id"`
	VisitedAt pgtype.Timestamp `json:"visited_at"`
	IpAddress pgtype.Text      `json:"ip_address"`
	UserAgent pgtype.Text      `json:"user_agent"`
}

type VisitLocation struct {
	VisitID     int32         `json:"visit_id"`
	Address     pgtype.Text   `json:"address"`
	CountryCode pgtype.Text   `json:"country_code"`
	CountryName pgtype.Text   `json:"country_name"`
	Subdivision pgtype.Text   `json:"subdivision"`
	Continent   pgtype.Text   `json:"continent"`
	CityName    pgtype.Text   `json:"city_name"`
	Latitude    pgtype.Float8 `json:"latitude"`
	Longitude   pgtype.Float8 `json:"longitude"`
	Source      pgtype.Text   `json:"source"`
}
