// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package datastore

import (
	"database/sql"
)

type Session struct {
	Key    string        `json:"key"`
	Data   []byte        `json:"data"`
	Expiry sql.NullInt64 `json:"expiry"`
}

type Url struct {
	ID        int64         `json:"id"`
	ShortUrl  string        `json:"short_url"`
	LongUrl   string        `json:"long_url"`
	AuthorID  sql.NullInt64 `json:"author_id"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type User struct {
	ID           int64        `json:"id"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	Password     string       `json:"password"`
	CreatedAt    sql.NullTime `json:"created_at"`
	PasswordSalt string       `json:"password_salt"`
}

type Visit struct {
	ID        int64          `json:"id"`
	UrlID     sql.NullInt64  `json:"url_id"`
	VisitedAt sql.NullTime   `json:"visited_at"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
}

type VisitLocation struct {
	VisitID     int64           `json:"visit_id"`
	Address     sql.NullString  `json:"address"`
	CountryCode interface{}     `json:"country_code"`
	CountryName sql.NullString  `json:"country_name"`
	Subdivision sql.NullString  `json:"subdivision"`
	Continent   sql.NullString  `json:"continent"`
	CityName    sql.NullString  `json:"city_name"`
	Latitude    sql.NullFloat64 `json:"latitude"`
	Longitude   sql.NullFloat64 `json:"longitude"`
	Source      sql.NullString  `json:"source"`
}
