// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package datastore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddShortURL(ctx context.Context, arg AddShortURLParams) (Url, error)
	GetShortURL(ctx context.Context, shortUrl string) (Url, error)
	GetUser(ctx context.Context, email string) (User, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	InsertVisitLocation(ctx context.Context, arg InsertVisitLocationParams) (VisitLocation, error)
	ListShortURLs(ctx context.Context, authorID pgtype.Int4) ([]Url, error)
	ListStatisticsPerAuthor(ctx context.Context, authorID pgtype.Int4) ([]ListStatisticsPerAuthorRow, error)
	ListVisits(ctx context.Context) ([]Visit, error)
	StatisticPerURL(ctx context.Context, arg StatisticPerURLParams) (StatisticPerURLRow, error)
	TrackRedirect(ctx context.Context, arg TrackRedirectParams) (Visit, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
