// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package datastore

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddShortURL(ctx context.Context, arg AddShortURLParams) (Url, error)
	GetShortURL(ctx context.Context, shortUrl string) (Url, error)
	GetUser(ctx context.Context, email string) (User, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	InsertVisitLocation(ctx context.Context, arg InsertVisitLocationParams) (VisitLocation, error)
	ListShortURLs(ctx context.Context, authorID sql.NullInt64) ([]Url, error)
	ListStatisticsPerAuthor(ctx context.Context, authorID sql.NullInt64) ([]ListStatisticsPerAuthorRow, error)
	ListVisits(ctx context.Context) ([]Visit, error)
	TrackRedirect(ctx context.Context, arg TrackRedirectParams) (Visit, error)
}

var _ Querier = (*Queries)(nil)
