// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: short_url.sql

package datastore

import (
	"context"
)

const addShortURL = `-- name: AddShortURL :one
INSERT INTO urls (title,short_url, long_url, author_id) 
VALUES ($1, $2, $3, $4)
RETURNING id, short_url, long_url, author_id, created_at, title
`

type AddShortURLParams struct {
	Title    string `json:"title"`
	ShortUrl string `json:"short_url"`
	LongUrl  string `json:"long_url"`
	AuthorID int32  `json:"author_id"`
}

func (q *Queries) AddShortURL(ctx context.Context, arg AddShortURLParams) (Url, error) {
	row := q.db.QueryRow(ctx, addShortURL,
		arg.Title,
		arg.ShortUrl,
		arg.LongUrl,
		arg.AuthorID,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortUrl,
		&i.LongUrl,
		&i.AuthorID,
		&i.CreatedAt,
		&i.Title,
	)
	return i, err
}

const getShortURL = `-- name: GetShortURL :one
SELECT id, short_url, long_url, author_id, created_at, title
FROM urls
WHERE urls.short_url = $1
`

func (q *Queries) GetShortURL(ctx context.Context, shortUrl string) (Url, error) {
	row := q.db.QueryRow(ctx, getShortURL, shortUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortUrl,
		&i.LongUrl,
		&i.AuthorID,
		&i.CreatedAt,
		&i.Title,
	)
	return i, err
}

const listShortURLs = `-- name: ListShortURLs :many
SELECT id, short_url, long_url, author_id, created_at, title
FROM urls
WHERE urls.author_id = $1
ORDER BY 
    CASE WHEN $2 = 'title_asc' THEN title END ASC,
    CASE WHEN $2 = 'title_desc' THEN title END DESC,
    CASE WHEN $2 = 'created_at_asc' THEN created_at END ASC,
    CASE WHEN $2 = 'created_at_desc' THEN created_at END DESC
`

type ListShortURLsParams struct {
	AuthorID int32       `json:"author_id"`
	SortBy   interface{} `json:"sort_by"`
}

func (q *Queries) ListShortURLs(ctx context.Context, arg ListShortURLsParams) ([]Url, error) {
	rows, err := q.db.Query(ctx, listShortURLs, arg.AuthorID, arg.SortBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Url{}
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.ShortUrl,
			&i.LongUrl,
			&i.AuthorID,
			&i.CreatedAt,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
