// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: statistics.sql

package datastore

import (
	"context"
	"database/sql"
)

const trackRedirect = `-- name: TrackRedirect :exec
INSERT INTO visits (url_id, ip_address, user_agent)
VALUES (?, ?, ?)
`

type TrackRedirectParams struct {
	UrlID     sql.NullInt64  `json:"url_id"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
}

func (q *Queries) TrackRedirect(ctx context.Context, arg TrackRedirectParams) error {
	_, err := q.db.ExecContext(ctx, trackRedirect, arg.UrlID, arg.IpAddress, arg.UserAgent)
	return err
}
