// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<footer class=\"bg-white border-t border-slate-200 mt-auto\"><div class=\"max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:px-8\"><div class=\"grid grid-cols-1 md:grid-cols-4 gap-8 mb-8\"><div class=\"col-span-1 md:col-span-1\"><a href=\"/\" class=\"text-indigo-600 font-bold text-xl flex items-center gap-2 mb-4\"><i class=\"fas fa-link\"></i> shortcut</a><p class=\"text-slate-400 text-sm\">Simplifying the web, one link at a time.</p></div><div><h4 class=\"font-semibold text-slate-900 mb-4\">Product</h4><ul class=\"space-y-2 text-sm text-slate-500\"><li><a href=\"#\" class=\"hover:text-indigo-600\">Features</a></li><li><a href=\"#\" class=\"hover:text-indigo-600\">Pricing</a></li><li><a href=\"#\" class=\"hover:text-indigo-600\">API</a></li></ul></div><div><h4 class=\"font-semibold text-slate-900 mb-4\">Company</h4><ul class=\"space-y-2 text-sm text-slate-500\"><li><a href=\"#\" class=\"hover:text-indigo-600\">About</a></li><li><a href=\"#\" class=\"hover:text-indigo-600\">Blog</a></li><li><a href=\"#\" class=\"hover:text-indigo-600\">Contact</a></li></ul></div><div><h4 class=\"font-semibold text-slate-900 mb-4\">Legal</h4><ul class=\"space-y-2 text-sm text-slate-500\"><li><a href=\"#\" class=\"hover:text-indigo-600\">Privacy</a></li><li><a href=\"#\" class=\"hover:text-indigo-600\">Terms</a></li></ul></div></div><div class=\"border-t border-slate-100 pt-8 flex flex-col md:flex-row justify-between items-center\"><p class=\"text-center text-sm text-slate-400\">&copy; 2025 Shortcut. All rights reserved.</p><div class=\"flex space-x-6 mt-4 md:mt-0 text-slate-400\"><a href=\"#\" class=\"hover:text-indigo-500\"><i class=\"fab fa-twitter\"></i></a> <a href=\"#\" class=\"hover:text-indigo-500\"><i class=\"fab fa-github\"></i></a> <a href=\"#\" class=\"hover:text-indigo-500\"><i class=\"fab fa-discord\"></i></a></div></div></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
