name: Deployment

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  build-container:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "actions/checkout@v4"
      - uses: extractions/setup-just@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      # - id: "auth"
      #   uses: "google-github-actions/auth@v2"
      #   with:
      #     project_id: "shortcut-425916"
      #     workload_identity_provider: "projects/520143610603/locations/global/workloadIdentityPools/github/providers/shortcut"
      - uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}" # Replace with the name of your GitHub Actions secret

      - name: Build
        run: |
          just build-deps
          just build

      - name: Build Docker image
        run: docker build -t ${{ vars.IMAGE_NAME }}:latest .

      - name: Configure Docker for pushing
        run: gcloud auth configure-docker ${{ vars.REGION }}-docker.pkg.dev

      # This deploys under 2 tags. One is `latest` and the other one is the last commit's SHA
      - name: ☁️ Deploy to GCP Artifact Registry
        run: |-
          docker tag ${{ vars.IMAGE_NAME }}:latest ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_NAME }}/${{ vars.REPOSITORY }}/${{ vars.IMAGE_NAME }}:latest
          docker tag ${{ vars.IMAGE_NAME }}:latest ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_NAME }}/${{ vars.REPOSITORY }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_NAME }}/${{ vars.REPOSITORY }}/${{ vars.IMAGE_NAME }}:latest
          docker push ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_NAME }}/${{ vars.REPOSITORY }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}
  
  deploy-cloudrun:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"
      pull-requests: write
          
    steps:
      - uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}" # Replace with the name of your GitHub Actions secret
          
      - id: "deploy-live"
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: "google-github-actions/deploy-cloudrun@v2"
        timeout-minutes: 10
        with:
          service: "shortcut"
          image: ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_NAME }}/${{ vars.REPOSITORY }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}
          region: ${{ vars.REGION }}
          revision_traffic: 'LATEST=100'

      - id: "deploy-preview"
        if: github.event_name == 'pull_request'
        uses: "google-github-actions/deploy-cloudrun@v2"
        timeout-minutes: 10
        with:
          service: "shortcut"
          image: ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_NAME }}/${{ vars.REPOSITORY }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}
          region: ${{ vars.REGION }}
          tag: ${{ github.head_ref }}
          no_traffic: true

      - name: Comment PR
        if: github.event_name == 'pull_request' && success()
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Revision deployed at ${{ steps.deploy-preview.outputs.url }}
          comment_tag: revision-url
          